[package]
name = "tosu-proxy"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1

[dependencies]
webbrowser = "1.0.2"
reqwest = { version = "0.12.9", features = ["rustls-tls", "charset", "json"] }
tokio = { version = "1.42.0", features = ["full"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
actix-web = "4.9.0"
actix-files = "0.6.6"