[package]
name = "tosu-proxy"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1

[dependencies]
bincode = "2.0.1"
regex = "1.11.1"
config = "0.15.11"
thiserror = "2.0.12"
salvo = { version = "0.77.1", features = ["default", "websocket"] }
tokio = { version = "1.44.1", features = ["rt-multi-thread", "process", "sync", "macros"] }
sea-orm = { version = "1.1.7", features = ["sqlx-sqlite", "sqlx-mysql", "sqlx-postgres", "runtime-tokio-native-tls", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = { version = "0.12.14", features = ["rustls-tls", "charset", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.134"
rand = "0.9.0"
futures-util = "0.3.31"

# old
actix-web = "4.9.0"
actix-ws = "0.3.0"
actix-cors = "0.7.0"
actix-files = "0.6.6"
