[package]
name = "tosu-proxy"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1

[dependencies]
reqwest = { version = "0.12.12", features = ["rustls-tls", "charset", "json"] }
tokio = { version = "1.44.0", features = ["process", "sync"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
actix-web = "4.9.0"
actix-ws = "0.3.0"
actix-cors = "0.7.0"
rand = "0.9.0"
actix-files = "0.6.6"
